Package Control autoinstall :)

diff --git a/st2install b/st2install
--- a/st2install
+++ b/st2install
@@ -30,17 +30,20 @@ STDOWNLOADURLLIKE="http://c758482.r82.cf2.rackcdn.com/Sublime Text "
 #Busquemos la ultima version de Sublime Text 2 en la web directamente
 STURLTOCHECK="`wget -qO- http://www.sublimetext.com/2`"
 
-echo "Sublime Text 2 Batch Installer/Upgrader (esteban@attitude.cl)"
+#Home del usuario (http://stackoverflow.com/questions/7358611/bash-get-users-home-directory-when-they-run-a-script-as-root)
+USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
+
+echo -e "\e[7m*** Sublime Text 2 Batch Installer/Upgrader (esteban@attitude.cl)\e[0m"
 
 #URL distinta segun sistema 64 o 32 bits
 if [ "i686" = `uname -m` ]; then
 	#http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1.tar.bz2
-	echo "System x86 detected"
+	echo -e "\e[7m*** System x86 detected.\e[0m"
 	#URLS="`grep -Po '(?<=href=").*?(?=">)' <<<"$STURLTOCHECK"`"
 	URL="`grep -Po '(?<=href="http://c758482.r82.cf2.rackcdn.com/Sublime Text )(.*?)([^x64].tar.bz2)(?=">)' <<<"$STURLTOCHECK"`"
 elif [ "x86_64" = `uname -m` ]; then
 	#http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.1%20x64.tar.bz2
-	echo "System x86_64 detected"
+	echo -e "\e[7m*** System x86_64 detected.\e[0m"
 	URL="`grep -Po '(?<=href="http://c758482.r82.cf2.rackcdn.com/Sublime Text )(.*?)(\w+ x64.tar.bz2)(?=">)' <<<"$STURLTOCHECK"`"
 fi
 
@@ -48,10 +51,10 @@ fi
 THEFILE="Sublime Text $URL"
 THEDOWNLOADURL="$STDOWNLOADURLLIKE$URL"
 
-echo "I will download and install $THEDOWNLOADURL for you :)"
+echo -e "\e[7m*** I will download and install $THEDOWNLOADURL for you :)\e[0m"
 
 #Instalamos Sublime Text 2
-echo "Creating temp location on /var/cache/..."
+echo -e "\e[7m*** Creating temp location on /var/cache/...\e[0m"
 mkdir -p /var/cache/sublime-text-2
 cd /var/cache/sublime-text-2
 
@@ -62,7 +65,7 @@ if [ -n "$APT_PROXIES" ]; then
 fi
 
 #Descargamos
-echo "Downloading file to temp location..."
+echo -e "\e[7m*** Downloading file to temp location...\e[0m"
 #http://unix.stackexchange.com/questions/37507/what-does-do-here
 :> wgetrc
 echo "noclobber = off" >> wgetrc
@@ -72,33 +75,33 @@ echo "verbose = on" >> wgetrc
 echo "progress = bar:default" >> wgetrc
 echo "tries = 3" >> wgetrc
 WGETRC=wgetrc wget --continue -O "$THEFILE" "$THEDOWNLOADURL" \
-	|| echo "Download failed."
+	|| echo -e "\e[7m***Download failed.\e[0m"
 	rm -f wgetrc
-echo "Download completed."
+echo -e "\e[7m*** Download completed.\e[0m"
 
-echo "Unpacking files on temp location..."
-tar xvf "$THEFILE" || echo "Cannot unpack downloaded file."
+echo -e "\e[7m*** Unpacking files on temp location...\e[0m"
+tar xvf "$THEFILE" || echo -e "\e[7m*** Cannot unpack downloaded file.\e[0m"
 
-echo "Installing Sublime Text 2 into /opt/sublime_text_2/"
+echo -e "\e[7m*** Installing Sublime Text 2 into /opt/sublime_text_2/\e[0m"
 mkdir -p /opt/sublime_text_2/
 cp -rf "/var/cache/sublime-text-2/Sublime Text 2/"* /opt/sublime_text_2/ #Carpeta diferente de ST3
 
-echo "Creating symlinks to /usr/bin/sublime_text"
+echo -e "\e[7m*** Creating symlinks to /usr/bin/sublime_text\e[0m"
 #ln -sf /opt/sublime_text_2/sublime_text /usr/bin/sublime_text #Usado en ST3
 ln -sf /opt/sublime_text_2/sublime_text /usr/bin/sublime-text-2
 ln -sf /opt/sublime_text_2/sublime_text /usr/bin/st2
 
-echo "Creating symlinks for icons on /usr/share/icons/hicolor/..."
+echo -e "\e[7m*** Creating symlinks for icons on /usr/share/icons/hicolor/...\e[0m"
 ln -sf /opt/sublime_text_2/Icon/128x128/sublime_text.png /usr/share/icons/hicolor/128x128/apps/sublime-text-2.png
 ln -sf /opt/sublime_text_2/Icon/256x256/sublime_text.png /usr/share/icons/hicolor/256x256/apps/sublime-text-2.png
 gtk-update-icon-cache /usr/share/icons/hicolor
 
-echo "Cleaning up temp unpacked files..."
+echo -e "\e[7m*** Cleaning up temp unpacked files...\e[0m"
 rm -rf "/var/cache/sublime-text-2/Sublime Text 2/" #Carpeta diferente de ST3
 rm -rf "/var/cache/sublime-text-2/"*.bz2
 
 #Creando archivo .desktop
-echo "Creating .desktop file (for easy launch and associate to Sublime Text 2)..."
+echo -e "\e[7m*** Creating .desktop file (for easy launch and associate to Sublime Text 2)...\e[0m"
 echo "[Desktop Entry]
 Version=1.0
 Type=Application
@@ -124,12 +127,22 @@ Name=New File
 Exec=/opt/sublime_text_2/sublime_text --command new_file
 OnlyShowIn=Unity;" > /usr/share/applications/"Sublime Text 2.desktop"
 
-#Instalar Package Control https://sublime.wbond.net/installation
-echo "Installing Package Control (check https://sublime.wbond.net/ for more awesomeness)..."
-mkdir -p "$HOME/.config/sublime-text-2/Installed Packages"
-wget  -O "$HOME/.config/sublime-text-2/Installed Packages/Package Control.sublime-package" "https://sublime.wbond.net/Package%20Control.sublime-package"
+#Porque necesitamos correr el comando como el usuario y no como root, usaremos:
+#http://superuser.com/questions/93385/run-part-of-a-bash-script-as-a-different-user
+#http://superuser.com/questions/195781/sudo-is-there-a-command-to-check-if-i-have-sudo-and-or-how-much-time-is-left
+CAN_I_RUN_SUDO=$(sudo -n uptime 2>&1|grep "load"|wc -l)
+if [ ${CAN_I_RUN_SUDO} -gt 0 ]; then
+	#Podemos correr sudo
+	#Instalar Package Control https://sublime.wbond.net/installation
+	echo -e "\e[7m*** Installing Package Control (check https://sublime.wbond.net/ for more awesomeness)...\e[0m"
+	sudo -u $SUDO_USER mkdir -p "$USER_HOME/.config/sublime-text-2/Installed Packages"
+	sudo -u $SUDO_USER wget -O "$USER_HOME/.config/sublime-text-2/Installed Packages/Package Control.sublime-package" "https://sublime.wbond.net/Package%20Control.sublime-package"
+else
+	#No podemos correr sudo
+	echo ''
+fi
 
-echo "That's all. Have fun Sublime Texting ;)"
+echo -e "\e[7m*** That's all. Have fun Sublime Texting ;)\e[0m"
 
 exit 0
 EOF
